TAPAAL/verifypn

.github/workflows/build-linux.yml, .github/workflows/build-win.yml, CMakeLists.txt, src/LTL/SuccessorGeneration/CMakeLists.txt, src/PetriEngine/PQL/CMakeLists.txt
Updated required version of bison to 3.7 (recent changes requies newer version of bison)
Moved find_package bison/flex to main cmake file
Updated github action scripts to install bison 3.7.6
=> Updated required bison version and depends

.github/workflows/build-linux.yml, .github/workflows/build-macos.yml, .github/workflows/build-win.yml, CMakeLists.txt
=> Updated CMake

boost_tests/utils.h, include/PetriEngine/Reachability/ReachabilityResult.h, src/CTL/CTLEngine.cpp, src/PetriEngine/Reachability/ResultPrinter.cpp, src/main.cpp
added output of empty trace when proposition is solved in initial marking + output when solved by TAR
=> Empty trace + TAR notification

src/main.cpp
Also output "Solved by Siphon-Trap" for AG
=> Siphon Traph Output

include/LTL/LTLToBuchi.h, src/LTL/Algorithm/LTLToBuchi.cpp, src/VerifyPN.cpp
Gives a few extra answers in LTL categories (tested on colored).
=> Ltl simplification

boost_tests/CMakeLists.txt, boost_tests/color_test.cpp, boost_tests/game_test.cpp, boost_tests/ltl_test.cpp, boost_tests/reachability_test.cpp, include/LTL/Algorithm/ModelChecker.h, include/LTL/Algorithm/NestedDepthFirstSearch.h, include/LTL/Algorithm/TarjanModelChecker.h, include/LTL/Structures/BitProductStateSet.h, include/LTL/SuccessorGeneration/ProductSuccessorGenerator.h, include/utils/structures/light_deque.h, src/LTL/Algorithm/NestedDepthFirstSearch.cpp, src/LTL/Algorithm/TarjanModelChecker.cpp, src/LTL/LTLSearch.cpp, src/main.cpp
Using PTries and light_dequeue in the LTL algorithms for speed and memory.
=> LTL ptries

boost_tests/color_test.cpp, boost_tests/models/unfolding_loop.pnml, boost_tests/models/unfolding_loop.xml, include/PetriEngine/Colored/BindingGenerator.h, include/PetriEngine/Colored/Intervals.h, src/PetriEngine/Colored/BindingGenerator.cpp
=> should solve the issue w. unfolding

include/LTL/LTLToBuchi.h, include/PetriEngine/Colored/Colors.h, include/PetriEngine/PQL/Expressions.h, include/PetriEngine/PQL/PredicateCheckers.h, include/PetriEngine/PQL/XMLPrinter.h, include/PetriEngine/options.h, src/LTL/Algorithm/LTLToBuchi.cpp, src/PetriEngine/PQL/Analyze.cpp, src/PetriEngine/PQL/Expressions.cpp, src/PetriEngine/PQL/PQLQueryParser.y, src/PetriEngine/PQL/PredicateCheckers.cpp, src/PetriEngine/PQL/QueryPrinter.cpp, src/PetriEngine/PQL/XMLPrinter.cpp, src/PetriParse/PNMLParser.cpp, src/PetriParse/QueryXMLParser.cpp
Fixing various issues w. parsing of colored models + wrong output for plus/multiplication expression + missing reductions for commutative expressions (+ and *).
=> Token count

Scripts/MCC22/competition-scripts/tapaal.sh
- adds fall-back if the unfolding/reduction-phase times-out or crashes.
- uses trap for cleanup of temporary files
- adds output of path to temporary files and reports errors if they cannot be created.
=> new script

include/PetriEngine/Reducer.h, src/PetriEngine/Reducer.cpp
fixes issues with the EFMNOP rule, leading to sub-par performance.
=> Mcc 2022 v2

Scripts/MCC22/competition-scripts/tapaal.sh, include/LTL/LTLValidator.h, src/main.cpp
fixing output, changing error to warning
=> Mcc2022 v3

CMakeLists.txt, spot-windows.patch
tries to patch the SPOT build pipeline to work with the GH build pipeline -- a combination which fails to correctly set flags for the MinGW cross compilation.
=> fix win build

CMakeLists.txt, spot-windows.patch, src/PetriEngine/Colored/Unfolder.cpp, src/PetriEngine/Reducer.cpp
fixing off-by-one error + consistency issue, both leading to undefined behaviour/segfaults
Fixes https://bugs.launchpad.net/tapaal/+bug/1983262
=> Inhibitor reduction err

include/LTL/LTLValidator.h
fixes https://bugs.launchpad.net/tapaal/+bug/1983373
=> missing check in ltl

include/PetriEngine/PQL/Analyze.h, include/PetriEngine/PQL/BinaryPrinter.h, include/PetriEngine/PQL/Evaluation.h, include/PetriEngine/PQL/FormulaSize.h, include/PetriEngine/PQL/PredicateCheckers.h, include/PetriEngine/PQL/PrepareForReachability.h, include/PetriEngine/PQL/PushNegation.h, include/PetriEngine/PQL/Simplifier.h, include/PetriEngine/PQL/XMLPrinter.h, src/PetriEngine/PQL/Analyze.cpp, src/PetriEngine/PQL/BinaryPrinter.cpp, src/PetriEngine/PQL/Evaluation.cpp, src/PetriEngine/PQL/FormulaSize.cpp, src/PetriEngine/PQL/PredicateCheckers.cpp, src/PetriEngine/PQL/PrepareForReachability.cpp, src/PetriEngine/PQL/PushNegation.cpp, src/PetriEngine/PQL/Simplifier.cpp, src/PetriEngine/PQL/XMLPrinter.cpp, src/PetriEngine/options.cpp
=> Added myself to contributors

.github/workflows/build-linux.yml, .github/workflows/build-macos.yml, .github/workflows/build-win.yml, src/LTL/Algorithm/TarjanModelChecker.cpp
=> Ltl trace fix

boost_tests/game_test.cpp, include/LTL/LTLValidator.h, include/PetriEngine/Synthesis/SimpleSynthesis.h, src/PetriEngine/Synthesis/SimpleSynthesis.cpp, src/main.cpp
=> Quantifier identification issues

include/PetriEngine/Reachability/ReachabilitySearch.h, include/PetriEngine/Structures/PotencyQueue.h, include/PetriEngine/options.h, src/PetriEngine/Reachability/ReachabilitySearch.cpp, src/PetriEngine/Structures/CMakeLists.txt, src/PetriEngine/Structures/PotencyQueue.cpp, src/PetriEngine/options.cpp
Implements a new search heuristic called Random Potency First Search
=> Random Potency First Search

include/CTL/SearchStrategy/BFSSearch.h, include/CTL/SearchStrategy/HeuristicSearch.h, include/PetriEngine/PQL/FormulaSize.h, include/PetriEngine/Structures/Queue.h, src/CTL/Algorithm/FixedPointAlgorithm.cpp, src/CTL/SearchStrategy/HeuristicSearch.cpp, src/PetriEngine/PQL/FormulaSize.cpp, src/PetriEngine/Structures/Queue.cpp
More randomness in searches + re-introduced CTL heuristics.
=> Improved searches

CMakeLists.txt, include/VerifyPN.h, src/PetriEngine/options.cpp, src/VerifyPN.cpp, src/main.cpp
Updated version number to 4.3.0, copyright year to 2023 and ordered contributers alphabetically
=> Srba patch 1

src/LTL/LTLSearch.cpp
=> fixing LTL loop+deadlock output for tarjan

src/PetriEngine/Reducer.cpp
Fixes https://bugs.launchpad.net/tapaal/+bug/2007298
=> fixed issue with trace-generation with application of ruleM

include/PetriEngine/Reachability/ReachabilitySearch.h
Added statisticsLevel condition on tryReach function.
@srba you can review it and merge it
=> Fix printStats StatisticsLevel condition 

.github/workflows/build-macos.yml, include/CTL/DependencyGraph/Configuration.h, include/CTL/DependencyGraph/Edge.h, include/CTL/SearchStrategy/SearchStrategy.h, include/PetriEngine/Colored/PnmlWriterColorExprVisitor.h, include/PetriEngine/PQL/Evaluation.h, include/PetriEngine/PQL/PushNegation.h, include/PetriEngine/PQL/Simplifier.h, include/PetriEngine/options.h, src/LTL/Algorithm/NestedDepthFirstSearch.cpp, src/PetriEngine/PQL/Evaluation.cpp, src/PetriEngine/PQL/PushNegation.cpp, src/PetriEngine/PQL/Simplifier.cpp, src/PetriEngine/options.cpp, src/VerifyPN.cpp
=> Hyperltl simplificaiton fix

include/PetriEngine/PQL/ColoredUseVisitor.h, src/PetriEngine/PQL/ColoredUseVisitor.cpp
=> adding missing visitors

src/LTL/LTLSearch.cpp
Fixes:
https://bugs.launchpad.net/tapaal/+bug/2051740
=> trace-list tag and name attribute missing for hyperLTL with one trace - fix 2051740

src/PetriEngine/Reducer.cpp
Fixes [bug 2079804](https://bugs.launchpad.net/tapaal/+bug/2079804).
Commit 9a542e89211231eb8c53cba9f7da02ccd844c3ef fixes the issue. In commit e0eddb189146ff43c1357d45812ced025849b7d4 I rewrite the applyRuleEP to be more clear about E vs P.
=> Fix rule P not checking initial marking

.github/workflows/build-linux.yml, include/PetriEngine/Colored/VariableVisitor.h, src/PetriEngine/Colored/BindingGenerator.cpp, src/PetriEngine/Colored/EvaluationVisitor.cpp
Fixes the nets attached in the following bug report:
https://bugs.launchpad.net/tapaal/+bug/2085693
=> Unfolding of subtractions with variables - fix 2085693

src/PetriEngine/Colored/Reduction/RedRuleParallelTransitions.cpp
Fixes bug https://bugs.launchpad.net/tapaal/+bug/2092210
=> Fixing a bug where a transition used in a query was removed.

CMakeLists.txt, include/PetriEngine/PQL/Contexts.h, include/PetriEngine/Simplification/LinearProgram.h, src/PetriEngine/Simplification/LinearProgram.cpp, src/VerifyPN.cpp
Fixes the bug https://bugs.launchpad.net/tapaal/+bug/2104268
=> Fixing a problem with passing uint32_t as int in the construction of LP

src/PetriEngine/ExplicitColored/ExplicitColoredInteractiveMode.cpp
Fixed printing of product colors printing wrong colors
=> Fixed printing of product colors

include/PetriEngine/Colored/ColoredNetStructures.h, include/PetriEngine/Colored/Expressions.h, src/PetriEngine/Colored/ColoredPetriNetBuilder.cpp, src/PetriEngine/Colored/ForwardFixedPoint.cpp
Fixes:
https://bugs.launchpad.net/tapaal/+bug/2120809
=> CPN fixed point subtraction - fix 2120809

src/PetriEngine/Colored/ForwardFixedPoint.cpp
Fixes:
https://bugs.launchpad.net/tapaal/+bug/2110113
Also fixes:
https://bugs.launchpad.net/tapaal/+bug/2109664
https://bugs.launchpad.net/tapaal/+bug/2110547
=> Fixed subtraction not enabled for input arcs - fix 2110113

src/PetriEngine/Colored/Unfolder.cpp
Fixes:
https://bugs.launchpad.net/tapaal/+bug/2111887
=> Inhibitor arc segfault - fix 2111887

boost_tests/color_test.cpp, boost_tests/models/fixpoint_and_partitioning_error.pnml, boost_tests/models/fixpoint_and_partitioning_error.xml, boost_tests/models/subtraction_bug.pnml, boost_tests/models/subtraction_bug.xml, boost_tests/models/subtraction_error_unfolding.pnml, boost_tests/models/subtraction_error_unfolding.xml, boost_tests/models/subtraction_error_unfolding_nonempty_marking.pnml, boost_tests/models/subtraction_error_unfolding_nonempty_marking.xml, boost_tests/models/subtraction_unfolding.pnml, boost_tests/models/subtraction_unfolding.xml, boost_tests/models/unfolding_and_overapprox_cpn_subtraction_error.pnml, boost_tests/models/unfolding_and_overapprox_cpn_subtraction_error.xml, boost_tests/utils.h
Adds additional colored tests for nets fixed in #202, #203, and #204.
Also simplifies some existing tests by deduplicating the code
=> Additional colored tests

src/PetriEngine/Simplification/LinearPrograms.cpp
Seems to fix:
https://bugs.launchpad.net/tapaal/+bug/2083918
=> Assertion failing in LP - fix 2083918
