TAPAAL/verifypn

include/PetriEngine/AbstractPetriNetBuilder.h
include/PetriEngine/Colored/ColoredPetriNetBuilder.h
include/PetriEngine/PetriNetBuilder.h
src/PetriEngine/Colored/ColoredPetriNetBuilder.cpp
src/PetriEngine/PetriNetBuilder.cpp
src/PetriParse/PNMLParser.cpp

Negative values for initial markings (and tokens) not needed. Changed to `uint32_t` from `int` in several places.
Most notably, the check for max numerical for initial marking was set to check `int` when in fact a `long long` was used. 
This made parsing for the model `GPPP-PT-C0010N1000000000` fail, as it has a marking of `4000000000`, which is larger than what an `int` can handle.
With the changes to the initial marking, and check of this, we can now parse `GPPP-PT-C0010N1000000000` and solve all queries in ReachabilityCardinality category (even very quickly, getting us some 16 more answers here), have not checked results in others. But at least we can now parse the model.
Made changes to other types, as we found this, but the main thing is with the initial marking.

Type of tokens during parsing

---

src/LTL/Algorithm/NestedDepthFirstSearch.cpp
src/LTL/Algorithm/TarjanModelChecker.cpp

TarJan and NestedDFS trace outputs included a unclosed <xml> tag, ignored in the gui. Removed to clean up.

Fixed issue where <?xml tag was included in trace output

---

src/PetriEngine/Colored/EvaluationVisitor.cpp

At a recent meeting with @petergjoel and @srba, we discussed the semantics of tuple-tuple comparisons on CPN guards. The engine uses lexicographical comparison according to Peter, but we do actually not know what the correct semantics are according to the pnml format.
This PR will make verifypn throw an exception if it encounters any tuple-tuple comparisons. I ran this branch on MCC2021 and can conclude that there are no tuple-tuple comparisons at the moment.

Throw error on tuple-tuple comparison

---

src/PetriEngine/Reducer.cpp

As it stands, the implementation of Rule E discards any possible reductions of transitions if the criteria to also remove the place are not fulfilled.
It also discards valid reductions in cases where a place has a transition that consumes tokens from the place without returning any to it, or where a transition returns exactly as many tokens to the place as it consumes from it.
Lastly, there is an unreachable assignment of initial markings that would be wrong if it was reachable.

Bring Rule E in line with the specification

---

src/PetriEngine/Reducer.cpp

New definition:
The new definition can reduces the following net, which was not possible before:
Performance improvements are tiny, but Rule C is applied more often, resulting in a smaller state space size in some cases. 
Reduction time:
State space size:

Generalize Rule C

---

include/CTL/DependencyGraph/Edge.h
src/CTL/Algorithm/CertainZeroFPA.cpp
src/CTL/PetriNets/OnTheFlyDG.cpp
src/LTL/Algorithm/TarjanModelChecker.cpp
src/LTL/Stubborn/SafeAutStubbornSet.cpp

This patch stops OnTheFlyDG from generating hyperedges $(v, T)$ where $v \in T$, as those edges cannot possibly improve the value of $v$ to 1 either way. This results in a good number of additional answers with no observed inconsistencies.
Note that doing this optimization in OnTheFlyDG gives a few more answers than doing it in CertainZeroFPA (as done in commit 2b913445 on this branch), and only does the check once per edge rather than each time an edge is checked, see benchmark below.
Benchmarks: number of queries solved, with 5 minutes and 15 GiB memory per query on mcc2021:
- Trunk 044327e8: 26908/37792 (71.2%) of answers.
- This branch, 2b913445: 27179/37792 (71.91%) of answers.
- CZero version, 9cc4a124 (earlier on this branch): 27162/37792 (71.87%) of answers.
This branch loses 19 …

Optimization in CTL: Discard hyperedges with self-loop

---

boost_tests/models/ltl_kbound.pnml
boost_tests/models/ltl_kbound.xml
include/CTL/CTLResult.h
include/CTL/PetriNets/OnTheFlyDG.h
include/LTL/Algorithm/ModelChecker.h
include/LTL/Algorithm/NestedDepthFirstSearch.h
include/LTL/Algorithm/TarjanModelChecker.h
include/LTL/LTLSearch.h
include/PetriEngine/Reachability/ReachabilitySearch.h
src/CTL/CTLEngine.cpp
src/CTL/CTLResult.cpp
src/CTL/PetriNets/OnTheFlyDG.cpp
src/LTL/Algorithm/NestedDepthFirstSearch.cpp
src/LTL/Algorithm/TarjanModelChecker.cpp
src/PetriEngine/Reachability/ReachabilitySearch.cpp
src/main.cpp

Adds token count output (and computation) to CTL. 
Notice that it is hard to say anything conclusive about CTL if we hit the bound.
For LTL, the trace is valid if we find a trace -- otherwise the result is inconclusive.

adding max token count to CTL statistics output

---

include/LTL/Algorithm/ModelChecker.h
include/LTL/Algorithm/NestedDepthFirstSearch.h
include/LTL/Algorithm/TarjanModelChecker.h
include/LTL/LTLSearch.h
include/LTL/Structures/BitProductStateSet.h
include/LTL/Structures/CompoundStateSet.h
include/PetriEngine/Structures/StateSet.h
src/CTL/CTLEngine.cpp
src/LTL/Algorithm/NestedDepthFirstSearch.cpp
src/LTL/Algorithm/TarjanModelChecker.cpp

Adds missing statistics for CTL when LTL and reachability engines are called on sub-goals of the formula.
Merge #122 first.

extended CTL Statistics

---

include/PetriEngine/Colored/Intervals.h

Fixes https://bugs.launchpad.net/tapaal/+bug/2012122
Fixes https://bugs.launchpad.net/tapaal/+bug/2012142

added missing default tuple size for empty tuples

---

include/PetriEngine/Structures/PotencyQueue.h
src/PetriEngine/Structures/PotencyQueue.cpp

The use of random sampling algorithm in RandomPotencyQueue::pop make the sorting of potencies useless when a value is pushed to the queue.

Removed the reorder of potencies in RPFS strategy

---

src/PetriEngine/PQL/Simplifier.cpp

If the query is trivial (false or true), then the result is true if (isTriviallyTrue XOR negated).
```
formula is trivially... | negated()   || result is...
false          | not negated ||  false
false          |   negated   ||  true
true           | not negated ||  true
true           |   negated   ||  false
```

Fix ControlCondition negation propagation

---

src/PetriEngine/Colored/Reduction/RedRuleRelevance.cpp

Fixes #155
The rule was mistakingly comparing the in-arc's expression with itself, while it was supposed to compare the expression on the in-arc and the out-arc.

Fix bug in colored reduction rule Relevance

---

src/PetriEngine/Reachability/ResultPrinter.cpp

Partially fixes the problem where CTL trace generator with disabled structural reductions didn't return the tokens in the trace, e.g. the bug report: https://bugs.launchpad.net/tapaal/+bug/2037313

Fixing problem with printing traces where reduction was disabled.

---

src/PetriEngine/PetriNetBuilder.cpp

I found this misplaced statement while looking through the PetriNetBuilder, possibly failing an assertion on the direction of arcs.
I ran the tests with `run_tests.sh` and no answers changed. However, I didn't give any options to the script since I do not know what the direction field is used for, so the test may not have tested anything. Let me know if I should rerun it with some specific options.

Bug fix in PetriNetBuilder regarding direction

---

include/PetriEngine/Colored/Unfolder.h
include/PetriEngine/options.h
include/VerifyPN.h
src/PetriEngine/Colored/Unfolder.cpp
src/PetriEngine/options.cpp
src/VerifyPN.cpp
src/main.cpp

Added the posibility to print bindings for CPNs whenever the trace option is different from NONE.

Print bidings for CPNs

---

include/PetriEngine/Stubborn/StubbornSet.h

This PR fixes an ordering-dependant bug in the stubborn set reductions involving presets consisting of mixed arcs and inhibitor arcs. The issue arises from a simple `inhib` flag which should only be updated whenever the corresponding `cand` index is updated.
**Example of wrong behavior:**
Consider the following Petri net and query `EF P0 = 0` ([stub_inhib_test.zip](https://github.com/TAPAAL/verifypn/files/15295037/stub_inhib_test.zip)).
- Running `./verifypn-linux64 stub_inhib_test.pnml stub_inhib_test.xml -x 1 -q 0 -r 0` results in "NOT satisfied",
- Running `./verifypn-linux64 stub_inhib_test.pnml stub_inhib_test.xml -x 1 -q 0 -r 0 -p` results in "satisfied".
The query should be satisfied with trace: T3 T0.

Fix stubborn reduction bug involving inhibitor arcs

---

.gitignore
include/PetriEngine/Colored/ArcIntervalVisitor.h
include/PetriEngine/Colored/ArcIntervals.h
include/PetriEngine/Colored/Expressions.h
include/PetriEngine/Colored/VariableVisitor.h
src/PetriEngine/Colored/EvaluationVisitor.cpp
src/PetriEngine/Colored/IntervalGenerator.cpp
src/PetriEngine/Colored/PartitionBuilder.cpp

Fixes:
https://bugs.launchpad.net/tapaal/+bug/2081147
By adding a extra empty map if right most expr is a VariableExpression or a tuple expression with a VariableExpression

Cpn unfolding - fix 2081147

---

src/PetriEngine/Colored/Reduction/RedRulePreemptiveFiring.cpp

The preemptive firing reduction can remove places if they have no pre places. However, the associated transition is not removed which causes the transition to be fireable arbitrarily many times. This PR deletes the transition as well.
I have attached an example net where this happens in the comments of the associated bug report. [direct link to the comment](https://bugs.launchpad.net/tapaal/+bug/2092210/comments/6)

Made preemptive firing reduction remove transition as well

---

src/PetriEngine/ExplicitColored/ExplicitColoredInteractiveMode.cpp

The engine ignores new markings send after the first one.
Try running interactive mode with the following net:
[interactive-test.txt](https://github.com/user-attachments/files/21748870/interactive-test.txt)
and give it the following sequence
1.
`<marking>
<place id="ComposedModel_P2">
<token count="1">
<color>1</color>
</token>
<token count="1">
<color>6</color>
</token>
</place>
</marking>`
2.
`<transition id="ComposedModel_T1">
<binding>
<variable id="x">
<color>1</color>
</variable>
</binding>
</transition>`
3.
`<marking>
<place id="ComposedModel_P3">
<token count="1">
<color>1</color>
</token>
</place>
<place id="ComposedModel_P2">
<token count="1">
<color>6</color>
</token>
</place>
</marking>`
the engine returns:
`<valid-bindings>
<transition id="ComposedModel_T1">
<binding> …

Engine ignoring new markings

---

src/PetriParse/PNMLParser.cpp

Engine fix for:
https://bugs.launchpad.net/tapaal/+bug/2120658

Colored inhibitor parsing does not match gui output - fix 2120658

---

.github/workflows/build-linux.yml
.github/workflows/build-win.yml
src/CTL/CMakeLists.txt
src/CTL/PetriNets/CMakeLists.txt
src/CTL/SearchStrategy/CMakeLists.txt
src/LTL/Algorithm/CMakeLists.txt
src/LTL/Simplification/CMakeLists.txt
src/LTL/Stubborn/CMakeLists.txt
src/LTL/SuccessorGeneration/CMakeLists.txt
src/PetriEngine/CMakeLists.txt
src/PetriEngine/Colored/Reduction/CMakeLists.txt
src/PetriEngine/ExplicitColored/CMakeLists.txt
src/PetriEngine/Stubborn/CMakeLists.txt
src/PetriEngine/Synthesis/CMakeLists.txt
src/PetriEngine/TAR/CMakeLists.txt
src/PetriParse/CMakeLists.txt

Uses more cores to build the binaries, resulting in a reduced usage time.
This required to update some dependency usages for some targets.

Multi-thread build
